version: '3.8'
services:
  mongo:
    image: mongo:4.4.18
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/travel-planner
      - NODE_ENV=development

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

volumes:
  mongo-data: